version: '3'
services:
  web:
    #build: .
    image: "<%= appName %>"
    volumes:
     - ./logs/<%= appName %>:/root/.pm2/logs
    environment:
     - API_SERVER=xxx.xxx.xxx.xxx:8000
     - API_PATH=/admin
     - HTTPS=false
    ports:
     - "8000:8000"